{% set name = "pdfstream" %}
{% set version = "0.6.0" %}
{% set sha256 = "dac32f481ced3b002e02b5efde508bf02afe5a3bb278261d18f6ea0f02e762fa" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  entry_points:
    - pdfstream = pdfstream.main:main
    - run_server = pdfstream.main:run_server
    - print_server_config_dir = pdfstream.main:print_server_config_dir
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - bluesky
    - databroker
    - fire
    - frozendict
    - numba
    - pyfai
    - pyopencl
    - scikit-beam
    - xpdview
    - xray-vision

test:
  imports:
    - pdfstream
  commands:
    - pdfstream -- --help

about:
  home: https://github.com/xpdAcq/pdfstream
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The data analysis toolbox for the study on pair distribution function (PDF).

extra:
  recipe-maintainers:
    - sbillinge
    - st3107
    - mrakitin
    - kbeeperez
    - conda-forge/event-model
