{% set name = "pdfstream" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pdfstream-{{ version }}.tar.gz
  sha256: dac32f481ced3b002e02b5efde508bf02afe5a3bb278261d18f6ea0f02e762fa

build:
  skip: true  # [py<37]
  entry_points:
    - pdfstream = pdfstream.main:main
    - run_server = pdfstream.main:run_server
    - print_server_config_dir = pdfstream.main:print_server_config_dir
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0

requirements:
  host:
    - python >=3.8, <3.10
    - pip
  run:
    - python >=3.8, <3.10
    - bluesky
    - databroker <2.0.0a
    - fire
    - frozendict
    - numba
    - pyfai
    - pyopencl
    - scikit-beam
    - xpdview
    - xray-vision

test:
  imports:
    - pdfstream
  commands:
    - pip check
    - pdfstream --help
    - run_server --help
    - print_server_config_dir --help
  requires:
    - pip

about:
  home: https://github.com/xpdAcq/pdfstream
  summary: The data analysis toolbox for the study on pair distribution function (PDF).
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - sbillinge
    - st3107
    - mrakitin
    - kbeeperez
    - conda-forge/event-model
