{% set name = "pdfstream" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pdfstream-{{ version }}.tar.gz
  sha256: f1d44a39cda1bc1b024f8a94d6e31225a1b2a94bcc9e8b6c6f2f8da3bf3596c8

build:
  noarch: python
  entry_points:
    - pdfstream = pdfstream.main:main
    - run_server = pdfstream.main:run_server
    - print_server_config_dir = pdfstream.main:print_server_config_dir
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - bluesky
    - databroker
    - fire
    - frozendict
    - numba
    - pyfai
    - pyopencl
    - scikit-beam
    - xpdview
    - xray-vision

test:
  imports:
    - pdfstream

about:
  home: https://github.com/xpdAcq/pdfstream
  summary: The data analysis toolbox for the study on pair distribution function (PDF).
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sbillinge
    - st3107
    - mrakitin
    - conda-forge/event-model
